### ISSUE TITLE
Android build failed : contentLength() is already defined in class RNFetchBlobBody

### ISSUE THREAD

**Issue by herve1976** [wkh237/react-native-fetch-blob#100]
/Users/herve76/Desktop/Fishii/node_modules/react-native-fetch-blob/android/src/main/java/com/RNFetchBlob/RNFetchBlobBody.java:107: error: method contentLength() is already defined in class RNFetchBlobBody
    public long contentLength() {
                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-fetch-blob:compileReleaseJavaWithJavac FAILED

**Comment by wkh237** [comment]
Could you tell me what's the version of the library?

**Comment by herve1976** [comment]
"react-native": "^0.31.0",
"react-native-fetch-blob": "^0.9.2",

**Comment by wkh237** [comment]
Try 0.9.3 that should be fixed : o

**Comment by herve1976** [comment]
I had to removed the duplicated lines to solve the build issue. but the android version is still not working

**Comment by wkh237** [comment]
Hi @herve1976 , what's the RN version of you app ? I've tested `0.9.3` on many environments (0.25~0.31) and I couldn't reproduce this error. I'd like to confirm if we already fixed this, I suppose this has been fixed in #98 . Please try reinstall the package 

```
$ rnpm uninstall react-native-fetch-blob
$ rnpm install react-native-fetch-blob
```

Thanks !
