### ISSUE TITLE
Upload to Firebase with Android images with prefix 'content://' fails to complete

### ISSUE THREAD

**Issue by MrRoyce** [wkh237/react-native-fetch-blob#110]
Hi there, I've been able to upload images to FireBase with the uri of type '/storage/emulated/0/DCIM/Camera/IMG_20160626_154052.jpg'  however, when I use the library, https://github.com/jeanpan/react-native-camera-roll-picker it returns the URI in the format 'content://media/external/images/media/20038' 

The uploads complete, but they only send a minimal amount of data (e.g. 31 bytes) to FireBase out of the 1.5m file?  

Is it a matter of the 'type' in the Blob.build and the 'contentType' in the put being set properly?

Also, do I assume I should not use theRNFetchBlob.wrap() with files with the 'content:' prefix?  I tried it with the wrap and it fails with the RN callback error and without the wrap() it fails as described above.

This is what I'm using now:

```
...
    Blob.build(rnfbURI, { type : 'image/jpg;BASE64'})  // rnfbURI is NOT wrapped 
    .then((blob) => {
      firebaseApp.storage()
        .ref('images')
        .child(testImageName)
        .put(blob, { contentType : 'image/jpg' })
        .then(() => {
          blob.close();
      })
...
```

Thanks again for you help.

**Comment by wkh237** [comment]
@MrRoyce , thanks for the information ! 

If you append `;BASE64` after the mime type string the library will try to decode the first argument as BASE64 encoded string, basically you can just pass `image/jpg` to `type`.

However, the Blob constructor only support file URI at this moment, passing an URI starts with  `content://` might not work as expected, but there's an workaround, you can copy the file using `fs.cp()` then upload the copy, here's an example

```js
  // tmp file path and tmp blob
  let tmp = fs.dirs.DocumentDir + '/tmp'+Date.now()
  let tmpBlob = null
  CameraRoll.getPhotos({first : 10})
    .then((resp) => {
      let url = resp.edges[0].node.image.uri
      // make a copy of the image in camera roll 
      return fs.cp(url, tmp)
    })
    .then(() => {
      // create Blob using the copy
      return Blob.build(RNFetchBlob.wrap(tmp), {type:'image/jpg'})
    })
    .then((b) => {
      blob = b
      // upload to Firebase
      return firebase.storage()
        .ref('rnfbtest').child('camra-roll-'+Date.now()+'.jpg')
        .put(b, {contentType : 'image/jpg'})
    })
    .then((snapshot) => {
      // remove temp file and release the blob instance
      blob.close()
    })
```

**Comment by matthieubessol** [comment]
@wkh237 thank you I also have the same problem. I tried your code, but when I do the upload to Firebase, it never ends. It won't go to the last step. 
Here is my blob : 
`{ listeners: {},
  isRNFetchBlobPolyfill: true,
  multipartBoundary: null,
  _ref: '/data/user/0/com.rndm/files/tmp1472509561234',
  _blobCreated: true,
  _closed: false,
  cacheName: 'blob-5999b6fb-dd73-499a-8705-728facaff680',
  type: 'image/jpg',
  size: '2463628' }
`

Don't know if it works for @MrRoyce .

Thanks  for your help.

**Comment by MrRoyce** [comment]
@wkh237 I was able to get the file upload to fire base working with the https://github.com/bamlab/rn-camera-roll library. That library converts the native android format 'content://...' to the iOS format 'file://..' 

@matthieubessol it worked for me from my device but only if debug is not on. So turn off 'debug external' and see if that works.

**Comment by wkh237** [comment]
@matthieubessol , does it happens on both IOS and Android ?

**Comment by matthieubessol** [comment]
@MrRoyce thanks it did not work in my case but I think it's a problem with my code. To be sure, if I've disable live reloadand js dev mode, that's enough ? 

@wkh237 I'm for the moment testing it only on my Android phone. 

In fact, I don't need the CameraRoll in my project. I have the path of a picture I took with [React-native-camera](https://github.com/lwansbrough/react-native-camera). The path is like that : `content://media/external/images/media/85761`. The problem is that I don't really understand how to handle that to create a blob and to send it with Firebase. 

Here is my code : 

`


       var self = this; 
       let tmp = fs.dirs.DocumentDir + '/tmp'+Date.now()
       let tmpBlob = null;
       
       var p = new Promise(
          function(resolve,reject) {
            let url = cameraUriPath; // something like content://media/external/images/media/85777
            resolve(fs.cp(url, tmp));
          }
        )

        p.then(() => {
          // create Blob using the copy
          return Blob.build(RNFetchBlob.wrap(tmp), {type:'image/jpg'});
        })
        .then((b) => {
          tmpBlob = b;
          // upload to Firebase
          return firebase.storage().ref('rnfbtest')
                    .child('camera-roll-'+Date.now()+'.jpg')
                    .put(b, {contentType : 'image/jpg'});
        })
        .then((snapshot) => { // Program never go there
          Alert.alert('Sent');
          // remove temp file and release the blob instance
          tmpBlob.close();
        })
        .catch((e) => {
          console.log(e);
          return;
        });`

There is certainly a problem with my code, I'm new to react-native and Firebase. 
It may be more a code problem than an issue.

**Comment by wkh237** [comment]
@MrRoyce @matthieubessol , I've published a prerelease version on npm `0.9.4-beta.2` which should be able to use extra URI such as`content://`, please try update the package and see if it works properly, also any feedback will be grateful, thank you 😄 

see [the test case](https://github.com/wkh237/react-native-fetch-blob/blob/0.9.4-beta.2/test/test-firebase.js#L179) for sample usage 👍

**Comment by matthieubessol** [comment]
I've juste tried it. It sends me an error : "The callback slice() exists in module RNFetchBlob, but only one callback may be registered to a function in a native mobile."

**Comment by matthieubessol** [comment]
@wkh237 thanqs again for the support. I'm now on the beta, but it still does nothing. I took the exact same code as test case. Here are my logs.
`'CameraRoll', 'content://media/external/images/media/85803'`
`start upload ..`

It strange, as soon as firebase make the call, there's nothing after.

**Comment by wkh237** [comment]
@matthieubessol , I'm a little confused about the code snippet you provided, looks like the promises will not wait for completion of `fs.cp`, I prefer do it this way

```diff

var self = this; 
   let tmp = fs.dirs.DocumentDir + '/tmp'+Date.now()
   let tmpBlob = null;

-   var p = new Promise(                                                                                                                                                          
-      function(resolve,reject) {                                                                                                                                                          
-       let url = cameraUriPath; // something like content://media/external/images/media/85777                                                                             
-        resolve(fs.cp(url, tmp));                                                                                                                                                                                                                                       
-      }                                                                                                                                                                                                                                                                                                                    

+ var p = fs.cp(url, tmp)                                                                                                                                                                                                                                       

    )
```

however, if you've upgrade to `0.9.4-beta.2` there's no need to copy the file before creating blob object, simply use the URI should be fine.

```js
    let url = cameraUriPath; // something like content://media/external/images/media/85777
    Blob.build(RNFetchBlob.wrap(tmp), {type:'image/jpg'});
    .then((b) => {
      tmpBlob = b;
      // upload to Firebase
      return firebase.storage().ref('rnfbtest')
                .child('camera-roll-'+Date.now()+'.jpg')
                .put(b, {contentType : 'image/jpg'});
    })
    .then((snapshot) => { // Program never go there
      Alert.alert('Sent');
      // if you don't want to remove the source file, do NOT close the blob
      // tmpBlob.close();
    })
    .catch((e) => {
      console.log(e);
      return;
    });

```

**Comment by matthieubessol** [comment]
@wkh237 yes, this is what I was testing. But still the same problem, at the moment Firebase should upload, it doesn't. Just nothing happens. I don't think it's because of the blob cause he seems good.

**Comment by matthieubessol** [comment]
@wkh237 it's working, don't know what I've changed though.

**Comment by abettilyon** [comment]
@matthieubessol , I'm having the same problem you are.  uploading to firebase storage just never happens.  Any hints on what you did to get it working?

**Comment by wkh237** [comment]
@abettilyon , would you mind provide sample code snippet, installed library, and RN version ?

**Comment by abettilyon** [comment]
Here is the upload function that I'm trying to run.

I've tried wrapping everything with await calls and it seems as though .build never finishes.  



```
export function upload_image( localFile, remoteFile ) {

  let rnfbURI = RNFetchBlob.wrap(localFile)

  try {
   RNFetchBlob.polyfill.Blob
    .build(rnfbURI, { type : 'image/png;'})
    .then( async (blob) => {
      // upload image using Firebase SDK
       Firebase.storage()
        .ref()
        .child("/images/" + remoteFile)
        .put(blob, { contentType : 'image/png' })
        .then((snapshot) => {
          /// upload success, code never gets here
          blob.close()
          done()
        })
    })
  }
  catch (err){
   // handle error (code never gets here)
  }

}
```

**Comment by abettilyon** [comment]
An update here, I've simplified the code significantly to try and troubleshoot.  

```javascript
  const Blob = RNFetchBlob.polyfill.Blob

  let rnfbURI = RNFetchBlob.wrap(localFile)
  let blb = await Blob.build( rnfbURI, { type: 'image/jpg'})
   console.log("GOT a BLOB!!!")
```


the console.log call never happens, as the Blob.build call never finishes.

**Comment by abettilyon** [comment]
Well, I feel silly.

When calling my upload_image function, I was passing the full react-native image object { uri: "/path/to/file" }.  I changed it to pass image.uri and it now works!

**Comment by abettilyon** [comment]
ARRGG!!  even though now I'm getting this from Firebase!
{"code":"storage/unknown","message":"Firebase Storage: An unknown error occurred, please check the error payload for server response.","serverResponse":"Multipart body does not contain 2 or 3 parts.","name":"FirebaseError"}

**Comment by wkh237** [comment]
@abettilyon , what does image.uri looks like ? if it has prefix `file://` you should remove it, and if you're creating blob from an existing file the file will be remove if you call `blob.close`

**Comment by abettilyon** [comment]
The magic I was missing was:

window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest;

After adding that, things started working as expected.  I actually DO want to call blob.close because I'm copying a newly created resized file from the original. 

Thanks for the help!

**Comment by farhanmannan** [comment]
@wkh237 sorry to wake up this old thread but I'm having a similar issue (`content://` urls), except I'm not trying to upload to Firebase. I'm uploading to a server that is expecting the request to have a `file` property. 

Client snippet:
```
// message.image is something like content://media/external/images/media/85777
console.log('****************** Sending now ************************');
        window.Blob = RNFetchBlob.polyfill.Blob;
        Blob.build(RNFetchBlob.wrap(message.image), { type: 'image/jpg' })
        .then((blob) => {
          console.log('BLOB•••••••••••••••••••••••', blob)
          RNFetchBlob.fetch(
            'POST',
            'http://192.168.0.4:3000/api/imageupload',
            { 'Content-Type': 'application/octet-stream' },
            { file: blob },
          )
          .uploadProgress((written, total) => { console.log('uploaded', written / total); })
          .progress((received, total) => { console.log('progress', received / total); })
          .then((res) => { console.log(res.text()); })
          .catch(console.log);
        });
```
Server snippet:
```
app.post('/api/imageupload', multer({ storage: multer.memoryStorage() }).single('file'), function(req, res) {
      console.log('\n |-------------------------')
        var mimeTypeImageMatch = /^image\/(jpe?g|png)$/i;
        if (!req.file) {
            // If no file
            console.log('************ this is the case that always happens **********************')
            return res.status(400).send('Expected file');
        } else if (!mimeTypeImageMatch.test(req.file.mimetype)) {
            // If not an image file
            return res.status(400).send('Expected image file');
        } else if (req.file.size > 1024 * 1024 * 50) {
            // If file too large (>50MB)
            return res.status(400).send('File too large');
        }
```
The `file` property is never there. Can you see what I'm missing here?
