### ISSUE TITLE
[iOS] Exception on openDocument (crashes app)

### ISSUE THREAD

**Issue by ChrisPikul510** [wkh237/react-native-fetch-blob#240]
Hi, awesome library. I'm currently having an issue on the iOS side of things when using `RNFetchBlob.ios.openDocument`. When opening a PDF I have downloaded as a test document the app crashes with an exception. I have tried with another document and it works fine, so I suppose it could somehow be a corrupt file. Either way though, I feel it should call the rejection so I can catch the error and resume operating instead of the current effect of just totally crashing.

Relevant open code (doesn't offer much help)
```
const path = "/var/mobile/Containers/Data/Application/17896C16-E88F-421A-9CFC-533FC7368752/Documents/App copy.pdf"
FetchBlob.ios.openDocument( path )
   .then(() => console.log('Previewing document', path))
   .catch((err) => console.error('Error opening document', err))
```

XCode Error from debug log
```
2017-01-23 16:28:47.025850 AppProject[1690:1517931] *** Assertion failure in -[UIDocumentInteractionController setURL:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.5.2/UIDocumentInteractionController.m:1012
2017-01-23 16:28:47.027 [fatal][tid:RNFetchBlob.queue] Exception 'UIDocumentInteractionController: invalid scheme (null).  Only the file scheme is supported.' was thrown while invoking openDocument on target RNFetchBlob with params (
    "file:///var/mobile/Containers/Data/Application/17896C16-E88F-421A-9CFC-533FC7368752/Documents/App copy.pdf",
    "<null>",
    442,
    443
)
```

This crash is happening on device, my simulator trials worked fine.

RN: 0.35
RNFetchBlob: 0.10
Device: iPhone 6 iOS 10.1.1

**Comment by ChrisPikul510** [comment]
Whoops sorry, I upgraded to 0.10.1 since I was at 0.10.0 and it does present an error now. My question is now becoming:

Why is the "scheme" not supported in this case? Is there a way to detect the exact problem with the file to avoid this in the future? Or is there basically nothing that can be done from here except to fail?

**Comment by wkh237** [comment]
@ChrisPikul510 , thanks for the information , will look into this issue.

**Comment by wkh237** [comment]
I've tested on latest `beta` version but not be able to replicate this issue, could you upgrade your package and try if it still happens ?

**Comment by ChrisPikul510** [comment]
@wkh237 Yeah sorry about that, the bug is corrected now. It was a problem with 0.10.0, so everything good to go now. Thanks!

**Comment by palmsey** [comment]
I ran into this too, and updating to 0.10.4 didn't fix it. I noticed this only happens with filenames that contain a space. I replaced the spaces with hyphens and the docs open fine now.
