### ISSUE TITLE
[QUESTION] How to use RNFetchBlob.fs.df() ?

### ISSUE THREAD

**Issue by ValBerthe** [wkh237/react-native-fetch-blob#302]
Using `react-native-fetch-blob 0.10.2`
Using xcode and iPhone 6S emulator, iOS 10.2
Using `react-native 0.42`

--- 
I am working on a project using RNFS, but since they recommend to use RNFetchBlob, I'm going to refactor everything. Among other features, I'm using RNFS's `getFSInfo()` in order to retrieve free storage space left. So, as 0.10.0 introduced `df()`, I would like to know how it works (wiki section is empty).

I have those noticeable differences : 

```
// RNFS
{
  totalSpace: 248828264448 (~ 248 GBytes)
  freeSpace: 216244088832 (~ 216 GBytes)
}

// RNFetchBlob
{
  free: 1495726032 (~ 1.5 GBytes)
  total: -279838720 (~ -279 MBytes)
}
```

Why those differences ? Is it a matter of emulator's storage/laptop storage ? Why is RNFetchBlob's `total` a negative number ?

**Comment by wkh237** [comment]
@ValBerthe , we've fixed the issue #276 but not yet release to npm. You can try to [install the package from branch](https://github.com/wkh237/react-native-fetch-blob/wiki#install-package-from-specific-branch-0100-only) `issue-276` and see if it's working properly, thanks!

**Comment by ValBerthe** [comment]
Updated to `RNFetchBlob 0.10.4`.

`df()` seems to still have a weird behavior. Now my output is : 

```
// RNFetchBlob
{
  free: -796413952 (~ -796 MBytes)
  total: -279838720 (~ -279 MBytes)
}
```

**Comment by wkh237** [comment]
@ValBerthe , I have committed a fix to branch `issue-301`, please try to install the package from the branch and see if that works.

**Comment by ValBerthe** [comment]
@wkh237 Updated `RNFetchBlob 0.10.4#issue-301` : 

Output is
```
{
  free: 492335104 (~ 492 MBytes)
  total: -279838720 (~ -279 MBytes)
}
```

Free space seems better, even though it is not the same value as expected by RNFS. Total space is still the same.

**Comment by wkh237** [comment]
@ValBerthe , thanks for quick response. I've just changed the implementation, you can install the package again from the same branch issue-302` now 👍

**Comment by ValBerthe** [comment]
@wkh237 Updated `RNFetchBlob 0.10.4#issue-302` : 

The output is the same as previously. Have you managed to run a working version of the feature ? Are `freeFileSystemSizeInBytes` and `fileSystemSizeInBytes` accurate enough ?

I'll check this out myself when I have a minute.

**Comment by wkh237** [comment]
@ValBerthe , I can only test it on the simulator but the result looks to make sense. 

![image](https://cloud.githubusercontent.com/assets/5063785/25045040/9da7b9c2-215c-11e7-9e6e-532256cf7be4.png)

Not sure if I missed something ?
